version: '3.2'

services:
  limesurvey:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 80
    networks: 
      - limesurvey
    depends_on:
      - mysql
    volumes:
      - tmp:/var/www/html/tmp
      - upload:/var/www/html/upload

  mysql:
    hostname: "ls_mysql"
    image: mysql:5
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - limesurvey
    environment:
      MYSQL_ROOT_PASSWORD: limesurvey
      MYSQL_DATABASE: limesurvey
      MYSQL_USER: limesurvey
      MYSQL_PASSWORD: limesurvey

volumes:
  mysql:
  tmp:
  upload:

networks:
  limesurvey:
    driver: overlay

